name: Push to simulation branch 🎈
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm run push-sim
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SCREEPS_AUTH_TOKEN: ${{secrets.SCREEPS_AUTH_TOKEN}}
